### ISSUE TITLE
Question: is exporting to STEP possible?

### ISSUE THREAD

**Issue by carlkl** [codelv/declaracad#13]

**Comment by frmdstryr** [comment]
Not at the moment. I'll try to add this when I get a chance.

**Comment by carlkl** [comment]
thanks for your support! I'm looking forward for this feature.

**Comment by frmdstryr** [comment]
Do you need any of the translation parameters defined here:  https://dev.opencascade.org/doc/overview/html/occt_user_guides__step.html#occt_step_3

**Comment by carlkl** [comment]
My guess is, that the OCCT defaults are OK for a first try, at least for me. I can't assess the expenses for a full parametric STEP export so I won't ask for that, at least for now...

**Comment by frmdstryr** [comment]
Ok, I added this now, please give it a try.

It's not exporting colors, will see if i can add that at some point.

**Comment by frmdstryr** [comment]
Please open a new issue if needed

**Comment by carlkl** [comment]
Just one more hint: The STEP export should be mentioned in the README.

**Comment by frmdstryr** [comment]
Thanks, I updated the readme.

>  I plan to use declaracad to feed a FEM tool with STEP files

Great! I'm interested to hear how it goes.
