### ISSUE TITLE
ModuleNotFoundError: No module named 'enaml.scintilla.themes'

### ISSUE THREAD

**Issue by ceremcem** [codelv/declaracad#14]
Current commit (https://github.com/codelv/declaracad/commit/6b8f7a0542d408156ab9fad99dff2f1e52ce1a8c) has this error on `python main.py`. 

# OS 

Debian 64bit, Conda3

# Workaround 

1. Create `requirements.txt` with the following contents: 

```
git+git://github.com/nucleic/atom
git+https://github.com/nucleic/enaml
```

then upgrade the modules: 

```
pip install --upgrade -r requirements.txt
```

This satisfies module requirement but currently throws the error: #15

**Comment by frmdstryr** [comment]
Thanks. As mentioned it currently requires the most recent versions of atom and enaml from github. Hopefully a release will be made soon.
