### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by DeadlyDad** [codelv/declaracad#27]
When right-clicking something in the Toolbox and selecting 'Show reference docs', DC hard crashes with a `ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'` error.  
Fixed with `pip install PyQtWebEngine`.

**Comment by frmdstryr** [comment]
Indeed, seems that was added a few months ago, it was originally builtin to PyQt5. 

Thanks for reporting this, I usually just use the browser instead of the help window...

**Comment by DeadlyDad** [comment]
(Just as aside, DC works **really** well with multiple monitors.)
![image](https://user-images.githubusercontent.com/13209333/77855893-5142d400-71a8-11ea-90c4-f83f1686dff8.png)

**Comment by frmdstryr** [comment]
Yeah the workbench framework it uses is really nice.

**Comment by DeadlyDad** [comment]
BTW, did you add in the needed installation of `git` & `service_identity`?

**Comment by frmdstryr** [comment]
Added in https://github.com/codelv/declaracad/commit/ad687b84ebd252e04b05626d23514b546737fcb6

Let me know if that's correct, I'm currently having issues getting my windows VM working...
