### ISSUE TITLE
Mirror using a plane not an axis?

### ISSUE THREAD

**Issue by tompaton** [codelv/declaracad#35]
I can't figure out how to get the `Mirror` operation to mirror on a plane, not an axis (which seems to have the effect of simply rotating an object (seems like this issue https://www.opencascade.com/content/mirroring-objects).

I've got this far:

```
from declaracad.occ.api import *

enamldef Leg(Part):
    Cut:
        Box: 
            dx = 3
            dy = 6
            dz = 10
            position = (-1.5, -3, 0)
                    
        Box:
            dx = 1.5
            dy = 3
            dz = 5
            position = (0, 0, 5)

enamldef Assembly(Part):
    Leg: leg:
        transparency = 0.25
        position = (5, 0, 0)
        
    Transform:
        shape = leg
        operations = [Mirror(z=1)]
        position = (-5, 0, 0)
```

And seeing:
![image](https://user-images.githubusercontent.com/530437/85202618-f8b84880-b34a-11ea-9822-f4c8c8e44c87.png)

Can you please provide an example if it is supported? Otherwise consider adding support?

**Comment by frmdstryr** [comment]
One confusing point on how the `Transform` is implemented, if `operations` is given then the `position` is ignored (maybe that should make that give an error?), see https://github.com/codelv/declaracad/blob/master/declaracad/occ/impl/occ_algo.py#L499. 

Instead just add a `Translate` to your operations list.

```python
# Created in DeclaraCAD
from declaracad.occ.api import *

enamldef Leg(Part):
    Cut:
        Box: 
            dx = 3
            dy = 6
            dz = 10
            position = (-1.5, -3, 0)
                    
        Box:
            dx = 1.5
            dy = 3
            dz = 5
            position = (0, 0, 5)

enamldef Assembly(Part):
    Leg: leg:
        transparency = 0.25
        position = (5, 0, 0)
        
    Transform:
        shape = leg
        operations = [Translate(x=5), Mirror(z=1)]

```

Another confusing thing with transforms is after the operation order matters, eg the same transform works with `operations = [Mirror(z=1), Translate(x=-5)]`

**Comment by tompaton** [comment]
The translation isn't the issue, it's the position of the cut out box that isn't "mirrored", but instead rotated, the desired output is the same as this model:

```from declaracad.occ.api import *

enamldef Leg(Part):
    Cut:
        Box: 
            dx = 3
            dy = 6
            dz = 10
            position = (-1.5, -3, 0)
                    
        Box:
            dx = 1.5
            dy = 3
            dz = 5
            position = (0, 0, 5)

enamldef MirroredLeg(Part):
    Cut:
        Box: 
            dx = 3
            dy = 6
            dz = 10
            position = (-1.5, -3, 0)
                    
        Box:
            dx = 1.5
            dy = 3
            dz = 5
            position = (-1.5, 0, 5)

enamldef Assembly(Part):
    Leg: leg:
        transparency = 0.25
        position = (5, 0, 0)
       
    MirroredLeg:
        position = (-5, 0, 0)```

![image](https://user-images.githubusercontent.com/530437/85212732-fbda2580-b398-11ea-9490-ba0944f3580d.png)

**Comment by frmdstryr** [comment]
Ah, sorry I misunderstood what you meant. 

I pushed an update (https://github.com/codelv/declaracad/commit/09c5c25ebd103926d847690d79a4052cbe80e6e4) which let's you specify the Mirror should be treated as  a plane instead of an axis (so it passes it as a gp_Ax2 as mentioned in the thread you found) by passing `plane=True` to the Mirror.

```python
# Created in DeclaraCAD
from declaracad.occ.api import *

enamldef Leg(Part):
    Cut:
        Box: 
            dx = 3
            dy = 6
            dz = 10
            position = (-1.5, -3, 0)
                    
        Box:
            dx = 1.5
            dy = 3
            dz = 5
            position = (0, 0, 5)

enamldef Assembly(Part):
    Leg: leg:
        transparency = 0.25
        position = (5, 0, 0)
        
    Transform:
        shape = leg
        operations = [Mirror(x=1, plane=True), Translate(x=-5)]
```  

Let me know if that helps.

**Comment by tompaton** [comment]
Yes, that's working perfectly, thanks!
