### ISSUE TITLE
Standalone Windows 64bit version of declaracad for testing

### ISSUE THREAD

**Issue by carlkl** [codelv/declaracad#42]
Hi,

I created an archive: [declaracad-win64_2020-07-03.7z](https://my.hidrive.com/lnk/KhAKjTj7) for testing declaracad on Windows. This link will expire in 3 months
This is not a frozen version but a standalone python with declaracad installed with pip together with all dependencies. The relevant parts of OCCT with its dependencies has been copied from a miniconda install. 

This archive is not meant for productive use but for testing the features of declaracad. 

At the moment there is no script to produce this kind of archive available.

**Comment by frmdstryr** [comment]
Great work, thank you!  This should make it easier for others so I pinned it for any other windows users that want to give it a try. 

It would be great if we could have ci build an installer by using something like [conda constructor](https://github.com/conda/constructor). I'm not sure what all is involved.

**Comment by carlkl** [comment]
Conda instructor is new for me, it looks promising. I will take a look on this, when I have time for that.

**Comment by DeadlyDad** [comment]
> Conda instructor is new for me, it looks promising. I will take a look on this, when I have time for that.

Might you have found time for this yet?  One option would be to generate a [PortableApps launcher](https://portableapps.com/manuals/PortableApps.comLauncher/).  That would make it downright _trivial_ for users to use it.  [Auto PY to EXE](https://github.com/brentvollebregt/auto-py-to-exe) could be the first step.

**Comment by carlkl** [comment]
@DeadlyDad, currently I'm not working on that. So far I had not received any feedback. If there is interest I may give it a try. 

Conda contructor looks more promising, as declaracad needs miniconda as a base system anyway. If this works it makes sense to use github actions as well. Due to my work load I do not want to promise anything for the near future.

**Comment by frmdstryr** [comment]
I updated the [release.py](https://github.com/codelv/declaracad/blob/master/release.py) script that uses [cx-freeze](https://cx-freeze.readthedocs.io/en/latest/), can someone that uses windows see if it works?

To build:
1. Install cx-freeze `pip install cx-freeze`
2. Run `python release.py build`
3. It should create a standalone version you can run in `build/<exe.something>/declaracad`

**Comment by carlkl** [comment]
closed - please use the artifacts from https://github.com/codelv/declaracad/actions
