### ISSUE TITLE
Save model as XBF

### ISSUE THREAD

**Issue by carlkl** [codelv/declaracad#45]
[CADAssistant](https://www.opencascade.com/release_notes/cad-assistant/) based on OCCT is a freeware tool to view and convert 3D models. AFAIK the BREP format retains all informations of a declaraced generated 3D model as it represents the underlying datamodell of OCCT.

I may be wrong, but I wonder if it is of advantage to save a model as BREP instead of the STEP format and use CADAssistant to convert to another format if needed.

**Comment by frmdstryr** [comment]
A new "Exporter" needs added under:
https://github.com/codelv/declaracad/tree/master/declaracad/occ/exporters

Then imported and included in the list here
https://github.com/codelv/declaracad/blob/master/declaracad/occ/plugin.py#L455

**Comment by carlkl** [comment]
I may be wrong with BREP, ist should be ath XBF Format, at least according to https://www.opencascade.com/products/cad-assistant/ 

```
XBF — BinXCAF, which is a binary persistence format for universal XCAF document structure 
used by OCCT. Format accumulates persistence of various data which can be imported from 
other files formats like STEP, IGES, ACIS, glTF, etc.
```

**Comment by carlkl** [comment]
closed due to low priority.

**Comment by frmdstryr** [comment]
You can leave this open. I looked at it the other day. 

The reason it's not as easy as some formats is because the CAF documents aren't currently used internally (as the code model itself makes it redundant). That said it's just a matter of figuring out how to use the document apis.

**Comment by carlkl** [comment]
I will reopen it, when I have a use case, where STEP files as exchange format are not sufficient.
