### ISSUE TITLE
when to use << as binding operator?

### ISSUE THREAD

**Issue by carlkl** [codelv/declaracad#46]
The enaml _subscription_ bindung operator `<<` is used in the documentation and examples on some places. However, it is not clear (to me) when to use `<<`  instead of the `=` operator.

**Comment by frmdstryr** [comment]
The difference is that `=` only sets the initial value but will not "observe" any changes to the expression while `<<` will trigger an update/regeneration of the model if something in the expression is modified later.

Typically using `=` will be fine. If you run into problems where some value is not being updated (or if you're lazy and don't care) use `<<`  .  I use `<<` when I think something might be changed just to be safe.

**Comment by carlkl** [comment]
Thanks for that insight. Mayy this should be added to the declaracd documentation too.
