### ISSUE TITLE
I've added DeclaraCAD to curated-code-cad

### ISSUE THREAD

**Issue by Irev-Dev** [codelv/declaracad#54]
First of all, nice project.

I've added the project to my ever-increasing curation of Code-CAD projects [repo](https://github.com/Irev-Dev/curated-code-cad), [webpage](https://kurthutten.com/blog/curated-code-cad/). Not having used DeclaraCAD I'm not in the best position to add a description but I've had a go at adding something. If you want to give me a paragraph or two summary I'd be happy to include it. Since it's in the context of lots of other similar projects, how its different is always a good point to make. What I've added so far is only.

### [DeclaraCAD](https://declaracad.com/)
- [Repo](https://github.com/codelv/declaracad)
- [Docs](https://declaracad.com/docs/introduction/)
- License: GPL-3

A declarative parametric 3D modelling program built using [OpenCASCADE](https://github.com/LaughlinResearch/pyOCCT)
and [enaml](https://github.com/nucleic/enaml/).

Oh btw @frmdstryr I noticed you're already following me. Maybe you didn't know about the curated repo, but if you did should have definitely suggested I include DeclaraCAD.

Also if you're interested I'm trying to get examples of the same [birdhouse](https://twitter.com/IrevDev/status/1340984905337982981) in as many of the different projects as possible. If you wanted to submit a PR of the birdhouse in DeclaraCAD that would be awesome, but no obligation obviously.

**Comment by frmdstryr** [comment]
Very nice, thanks!

Here's one way to do the birdhouse.

```python
# Created in DeclaraCAD
from math import radians
from declaracad.occ.api import *
from declaracad.parts.display import Axis


enamldef Birdhouse(Part): part:
    attr width = 120
    attr height = 85
    attr thickness = 2
    attr hole_radius = 28
    attr hook_height = 10
    
    Fuse: house:
        material = 'brass'
        
        Cut: first_side:
            ThickSolid: 
                # Offset is negative so the corners are squared instead of rounded
                offset = -thickness
                faces = children[0].topology.faces[3:5]
                Extrude: 
                    vector = (0, width, 0)
                    Face:
                        Polygon: profile:
                            # Polygon centered around the y axis
                            attr w = -width/2
                            points = [
                                (w, w),
                                (0, w, height),
                                (width/2, w, 0),
                            ]
            Cylinder: hole:
                position = (-width/2, 0, height/4+thickness)
                direction = (1, 0, 0)
                radius = hole_radius
                height = width
        
        Transform: second_side:
            operations = [Rotate(angle=radians(90))]
            shape = first_side
    
        Transform: hook:
            position = (0, -thickness/2, height)
            Extrude:
                vector = (0, thickness, 0)
                Face:
                    Wire: hook_profile:
                        Polyline: hook_half_profile:
                            attr w = width /4
                            points = [
                                (0, 0, hook_height/3),
                                (5, 0, -thickness),
                                (w, 0, -thickness),
                                (5, 0, hook_height),
                                (0, 0, hook_height),
                            ]
                        Transform:
                            operations = [Mirror(z=1)]
                            shape = hook_half_profile

        
enamldef Assembly(Part):
    Axis: # Display origin axis
        color = 'black'
    Plane: # Display a ground plane
        color = 'white'
        bounds = [(-1000, -1000), (1000, 1000)]
    Birdhouse:
        pass

```
![birdhouse](https://user-images.githubusercontent.com/380158/104467014-d5bde200-5583-11eb-9337-195bbf1981de.png)

**Comment by Irev-Dev** [comment]
Thanks @frmdstryr
